version: '3'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/simple_login_register
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_PATH=redis://redis:6379/1
